### ISSUE TITLE
运行不了

### ISSUE THREAD

**Issue by jeremy16601** [qianjiahao/friends-circle#1]
friends-circle/node_modules/mongoose/node_modules/mongodb/lib/server.js:228
        process.nextTick(function() { throw err; })
                                            ^
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete](net.js:1010:19)

**Comment by qianjiahao** [comment]
这个问题应该是friends-circle的端口跟你的程序的端口冲突了，可以尝试

```
 ps -A 
```

找一下有冲突的端口，然后

```
  kill -15 PID （id 号）
```

然后杀掉他

如果方便的话，请重新clone一下程序，最新版是1.0.1，今天早上把之前的一些小bug修补了一下。 ^ - ^
