### ISSUE TITLE
为什么要去安装net 2.0 和 vs 2005啊

### ISSUE THREAD

**Issue by albb762** [qianjiahao/friends-circle#2]
net2.0 装不了，使用不了你的软件。为什么要这么多依赖啊，而且不是最新版的

**Comment by qianjiahao** [comment]
这个问题我还真没有见过。。。因为没有使用net2.0等微软相关的东西，如果你确认安装了bower和npm，那可能是撞墙导致的这个问题，能否截个图，我看下错误log
